#!/usr/bin/env python3
"""
Manual Verification Pipeline for AI-TD Research

Creates verification forms, collects expert annotations, and calculates
inter-annotator agreement (Cohen's κ) for dataset validation.

Usage:
    python scripts/manual_verification.py --dataset data/sample_research_dataset.csv --sample 10
    python scripts/manual_verification.py --form data/verification_form.json --annotate
    python scripts/manual_verification.py --calculate-kappa reviewer1.json reviewer2.json
"""

import argparse
import json
import random
from pathlib import Path
from typing import Dict, List, Tuple

import pandas as pd
import numpy as np
from sklearn.metrics import cohen_kappa_score


class ManualVerificationPipeline:
    """Pipeline for manual verification of AI-generated code classification."""
    
    def __init__(self):
        self.verification_dir = Path("data/verification")
        self.verification_dir.mkdir(exist_ok=True)
        
        # Debt Severity Rubric (from research proposal)
        self.rubric = {
            0: {
                'level': 'None',
                'definition': 'No observable maintainability issue',
                'criteria': [
                    'Function < 20 lines',
                    'Has complete docstring',
                    'Proper error handling',
                    'Clear variable names',
                    'No code duplication'
                ],
                'ai_examples': 'Well-written code with documentation'
            },
            1: {
                'level': 'Minor',
                'definition': 'Minor issue, easy to refactor',
                'criteria': [
                    'Variable names unclear',
                    'Magic numbers without constants',
                    'Missing comments for complex logic',
                    'Minor formatting issues'
                ],
                'ai_examples': 'AI code with minor naming issues'
            },
            2: {
                'level': 'Moderate',
                'definition': 'Noticeable structural/design problem',
                'criteria': [
                    'Function > 50 lines',
                    'Complex logic without abstraction',
                    'Clear code duplication',
                    'Missing error handling in risky calls',
                    'Deep nesting (> 3 levels)'
                ],
                'ai_examples': 'AI code with duplication and missing docs'
            },
            3: {
                'level': 'Severe',
                'definition': 'Severe issue impacting maintainability',
                'criteria': [
                    'Cyclomatic complexity > 20',
                    'No error handling at all',
                    'Deep nested loops (> 4 levels)',
                    'Copy-paste code > 30 lines',
                    'No documentation whatsoever'
                ],
                'ai_examples': 'Typical AI-generated code with multiple issues'
            }
        }
        
        # AI identification criteria
        self.ai_identification_criteria = [
            'Has explicit AI commit markers (e.g., "generated by copilot")',
            'Repository owner confirms AI usage',
            'Code patterns match LLM output (e.g., generic variable names)',
            'High duplication rate (> 20%)',
            'Missing documentation despite complexity',
            'Inconsistent coding style within files',
            'Unusual comment patterns or lack thereof'
        ]
    
    def select_sample_for_verification(self, dataset_path: str, sample_size: int = 10) -> pd.DataFrame:
        """
        Select stratified random sample for manual verification.
        
        Selects repositories stratified by:
        - AI confidence level (High/Medium/Low/None)
        - Language (Python/JS/TS)
        - Size tier (Small/Medium/Large)
        """
        print(f"Selecting {sample_size} repositories for verification from {dataset_path}...")
        
        df = pd.read_csv(dataset_path)
        
        # Create size tiers
        df['size_tier'] = pd.cut(df['size_kb'], 
                                  bins=[0, 15000, 35000, 50000], 
                                  labels=['Small', 'Medium', 'Large'])
        
        # Stratified sampling
        samples = []
        
        # Ensure representation from each AI confidence level
        confidence_levels = df['ai_confidence'].unique()
        repos_per_level = sample_size // len(confidence_levels)
        
        for conf_level in confidence_levels:
            conf_df = df[df['ai_confidence'] == conf_level]
            if len(conf_df) > 0:
                # Further stratify by language and size
                sample = conf_df.groupby(['language', 'size_tier'], group_keys=False).apply(
                    lambda x: x.sample(min(1, len(x)), random_state=42)
                )
                
                # Fill remaining quota randomly
                remaining = repos_per_level - len(sample)
                if remaining > 0 and len(conf_df) > len(sample):
                    additional = conf_df[~conf_df.index.isin(sample.index)].sample(
                        min(remaining, len(conf_df) - len(sample)), random_state=42
                    )
                    sample = pd.concat([sample, additional])
                
                samples.append(sample)
        
        if samples:
            final_sample = pd.concat(samples).head(sample_size)
        else:
            final_sample = df.sample(min(sample_size, len(df)), random_state=42)
        
        print(f"Selected {len(final_sample)} repositories for verification")
        print(f"  AI confidence distribution: {final_sample['ai_confidence'].value_counts().to_dict()}")
        if 'language' in final_sample.columns:
            print(f"  Language distribution: {final_sample['language'].value_counts().to_dict()}")
        else:
            print(f"  Language column not available in dataset")
        
        return final_sample
    
    def create_verification_form(self, sample_df: pd.DataFrame, output_path: str):
        """
        Create verification form for expert reviewers.
        """
        print(f"Creating verification form with {len(sample_df)} repositories...")
        
        form = {
            'metadata': {
                'created_at': pd.Timestamp.now().isoformat(),
                'total_repositories': len(sample_df),
                'rubric_version': '1.0',
                'reviewer_instructions': [
                    'Review each repository independently',
                    'Do not discuss with other reviewers until both complete',
                    'Use the 4-point rubric (0=None, 1=Minor, 2=Moderate, 3=Severe)',
                    'AI identification: Score confidence 0-3 based on evidence'
                ]
            },
            'rubric': self.rubric,
            'ai_identification_criteria': self.ai_identification_criteria,
            'repositories': []
        }
        
        for idx, row in sample_df.iterrows():
            repo_entry = {
                'repo_id': idx,
                'name': row.get('name', ''),
                'url': row.get('url', ''),
                'language': row.get('language', ''),
                'size_kb': int(row.get('size_kb', 0)),
                'ai_commit_ratio': float(row.get('ai_commit_ratio', 0)),
                'ai_confidence_auto': row.get('ai_confidence', ''),
                'verification': {
                    'ai_identification_score': None,  # 0-3: 0=Definitely Human, 3=Definitely AI
                    'ai_identification_confidence': None,  # 0-3 scale
                    'ai_identification_evidence': [],  # Which criteria apply
                    'debt_severity_scores': {
                        'complexity': None,  # 0-3
                        'duplication': None,  # 0-3
                        'documentation': None,  # 0-3
                        'error_handling': None,  # 0-3
                    },
                    'overall_debt_severity': None,  # 0-3
                    'comments': '',
                    'reviewed_at': None,
                    'reviewer_id': None
                }
            }
            form['repositories'].append(repo_entry)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(form, f, indent=2, ensure_ascii=False)
        
        print(f"Verification form saved to {output_path}")
        
        # Also create CSV version for easy editing
        csv_path = output_path.replace('.json', '.csv')
        sample_df.to_csv(csv_path, index=False)
        print(f"Sample list saved to {csv_path}")
        
        return form
    
    def create_blank_annotation_form(self, sample_size: int = 10, output_path: str = None):
        """Create blank annotation form with sample repositories for testing."""
        if output_path is None:
            output_path = str(self.verification_dir / "blank_verification_form.json")
        
        print(f"Creating blank annotation form with {sample_size} sample entries...")
        
        form = {
            'metadata': {
                'created_at': pd.Timestamp.now().isoformat(),
                'form_type': 'blank_template',
                'total_repositories': sample_size,
                'instructions': 'Fill in repository details and scores for manual verification study'
            },
            'rubric': self.rubric,
            'ai_identification_criteria': self.ai_identification_criteria,
            'repositories': []
        }
        
        # Create blank entries
        for i in range(sample_size):
            repo_entry = {
                'repo_id': i,
                'name': f'repository-{i+1}',
                'url': f'https://github.com/owner/repo-{i+1}',
                'language': random.choice(['Python', 'JavaScript', 'TypeScript']),
                'verification': {
                    'ai_identification_score': None,
                    'ai_identification_confidence': None,
                    'ai_identification_evidence': [],
                    'debt_severity_scores': {
                        'complexity': None,
                        'duplication': None,
                        'documentation': None,
                        'error_handling': None,
                    },
                    'overall_debt_severity': None,
                    'comments': '',
                    'reviewed_at': None,
                    'reviewer_id': None
                }
            }
            form['repositories'].append(repo_entry)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(form, f, indent=2, ensure_ascii=False)
        
        print(f"Blank annotation form saved to {output_path}")
        return form
    
    def calculate_cohens_kappa(self, reviewer1_path: str, reviewer2_path: str) -> Dict:
        """
        Calculate Cohen's κ for inter-annotator agreement.
        
        Args:
            reviewer1_path: JSON file with reviewer 1 annotations
            reviewer2_path: JSON file with reviewer 2 annotations
            
        Returns:
            Dictionary with kappa scores for different metrics
        """
        print(f"Calculating Cohen's kappa between {reviewer1_path} and {reviewer2_path}...")
        
        with open(reviewer1_path, 'r') as f:
            r1_data = json.load(f)
        with open(reviewer2_path, 'r') as f:
            r2_data = json.load(f)
        
        results = {}
        
        # Extract scores for each metric
        metrics = [
            'ai_identification_score',
            'overall_debt_severity',
            'debt_severity_scores.complexity',
            'debt_severity_scores.duplication',
            'debt_severity_scores.documentation',
            'debt_severity_scores.error_handling'
        ]
        
        for metric in metrics:
            r1_scores = []
            r2_scores = []
            
            for r1_repo, r2_repo in zip(r1_data['repositories'], r2_data['repositories']):
                if metric == 'debt_severity_scores.complexity':
                    r1_score = r1_repo['verification']['debt_severity_scores'].get('complexity')
                    r2_score = r2_repo['verification']['debt_severity_scores'].get('complexity')
                elif metric == 'debt_severity_scores.duplication':
                    r1_score = r1_repo['verification']['debt_severity_scores'].get('duplication')
                    r2_score = r2_repo['verification']['debt_severity_scores'].get('duplication')
                elif metric == 'debt_severity_scores.documentation':
                    r1_score = r1_repo['verification']['debt_severity_scores'].get('documentation')
                    r2_score = r2_repo['verification']['debt_severity_scores'].get('documentation')
                elif metric == 'debt_severity_scores.error_handling':
                    r1_score = r1_repo['verification']['debt_severity_scores'].get('error_handling')
                    r2_score = r2_repo['verification']['debt_severity_scores'].get('error_handling')
                else:
                    r1_score = r1_repo['verification'].get(metric)
                    r2_score = r2_repo['verification'].get(metric)
                
                if r1_score is not None and r2_score is not None:
                    r1_scores.append(r1_score)
                    r2_scores.append(r2_score)
            
            if r1_scores and r2_scores:
                kappa = cohen_kappa_score(r1_scores, r2_scores)
                
                # Interpretation
                if kappa < 0:
                    interpretation = 'poor (less than chance)'
                elif kappa < 0.20:
                    interpretation = 'slight agreement'
                elif kappa < 0.40:
                    interpretation = 'fair agreement'
                elif kappa < 0.60:
                    interpretation = 'moderate agreement'
                elif kappa < 0.80:
                    interpretation = 'substantial agreement'
                else:
                    interpretation = 'almost perfect agreement'
                
                results[metric] = {
                    'kappa': round(kappa, 4),
                    'interpretation': interpretation,
                    'n_samples': len(r1_scores),
                    'rater1_mean': round(np.mean(r1_scores), 2),
                    'rater2_mean': round(np.mean(r2_scores), 2)
                }
        
        # Overall summary
        avg_kappa = np.mean([r['kappa'] for r in results.values() if 'kappa' in r])
        results['overall'] = {
            'average_kappa': round(avg_kappa, 4),
            'adequate': avg_kappa >= 0.60,
            'target': 0.60,
            'metrics_evaluated': len(results) - 1  # Exclude 'overall' itself
        }
        
        return results
    
    def print_kappa_report(self, results: Dict):
        """Print formatted κ report."""
        print("\n" + "="*60)
        print("INTER-ANNOTATOR AGREEMENT REPORT")
        print("="*60)
        
        for metric, data in results.items():
            if metric == 'overall':
                continue
            
            print(f"\n{metric}:")
            print(f"  Cohen's κ: {data['kappa']:.4f}")
            print(f"  Interpretation: {data['interpretation']}")
            print(f"  Samples: {data['n_samples']}")
            print(f"  Rater 1 mean: {data['rater1_mean']}")
            print(f"  Rater 2 mean: {data['rater2_mean']}")
        
        overall = results.get('overall', {})
        print(f"\n{'='*60}")
        print("OVERALL SUMMARY")
        print(f"{'='*60}")
        print(f"Average κ across all metrics: {overall.get('average_kappa', 'N/A')}")
        print(f"Target (≥0.60): {'✓ PASSED' if overall.get('adequate') else '✗ FAILED'}")
        print(f"Metrics evaluated: {overall.get('metrics_evaluated', 0)}")
        print("="*60)
    
    def generate_mock_annotations(self, form_path: str, reviewer_id: str, output_path: str):
        """Generate mock annotations for testing κ calculation."""
        print(f"Generating mock annotations for reviewer {reviewer_id}...")
        
        with open(form_path, 'r') as f:
            form = json.load(f)
        
        # Generate realistic mock scores
        for repo in form['repositories']:
            is_ai = 'ai' in repo['name'].lower() or random.random() > 0.5
            
            if is_ai:
                # AI repos get higher severity scores with some variation
                base_severity = random.choices([1, 2, 3], weights=[0.2, 0.5, 0.3])[0]
                ai_score = random.choices([2, 3], weights=[0.3, 0.7])[0]
            else:
                # Human repos get lower severity scores
                base_severity = random.choices([0, 1, 2], weights=[0.4, 0.4, 0.2])[0]
                ai_score = random.choices([0, 1], weights=[0.7, 0.3])[0]
            
            # Add some reviewer variation (±1 level)
            variation = random.choice([-1, 0, 0, 0, 1])
            
            repo['verification']['ai_identification_score'] = max(0, min(3, ai_score + variation))
            repo['verification']['ai_identification_confidence'] = random.randint(1, 3)
            repo['verification']['ai_identification_evidence'] = random.sample(
                self.ai_identification_criteria, 
                k=random.randint(1, 3)
            )
            
            for dim in ['complexity', 'duplication', 'documentation', 'error_handling']:
                dim_score = max(0, min(3, base_severity + random.choice([-1, 0, 0, 1])))
                repo['verification']['debt_severity_scores'][dim] = dim_score
            
            repo['verification']['overall_debt_severity'] = max(0, min(3, base_severity + variation))
            repo['verification']['comments'] = f'Mock annotation by {reviewer_id}'
            repo['verification']['reviewed_at'] = pd.Timestamp.now().isoformat()
            repo['verification']['reviewer_id'] = reviewer_id
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(form, f, indent=2, ensure_ascii=False)
        
        print(f"Mock annotations saved to {output_path}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Manual Verification Pipeline")
    parser.add_argument("--dataset", help="Dataset CSV file to sample from")
    parser.add_argument("--sample", type=int, default=10, help="Sample size for verification")
    parser.add_argument("--form", help="Verification form JSON file")
    parser.add_argument("--annotate", action="store_true", help="Create annotation interface")
    parser.add_argument("--calculate-kappa", nargs=2, help="Calculate κ between two reviewer files")
    parser.add_argument("--create-blank", type=int, help="Create blank form with N entries")
    parser.add_argument("--generate-mock", nargs=2, help="Generate mock annotations (form_path reviewer_id)")
    
    args = parser.parse_args()
    
    pipeline = ManualVerificationPipeline()
    
    if args.dataset:
        # Select sample and create form
        sample_df = pipeline.select_sample_for_verification(args.dataset, args.sample)
        form_path = f"data/verification_form_{args.sample}repos.json"
        pipeline.create_verification_form(sample_df, form_path)
        print(f"\nNext steps:")
        print(f"1. Send {form_path} to 2 independent reviewers")
        print(f"2. Collect completed forms as reviewer1.json and reviewer2.json")
        print(f"3. Run: python scripts/manual_verification.py --calculate-kappa reviewer1.json reviewer2.json")
    
    elif args.create_blank:
        # Create blank form for testing
        pipeline.create_blank_annotation_form(args.create_blank)
    
    elif args.generate_mock:
        # Generate mock annotations
        form_path, reviewer_id = args.generate_mock
        output_path = f"data/verification/reviewer_{reviewer_id}_mock.json"
        pipeline.generate_mock_annotations(form_path, reviewer_id, output_path)
    
    elif args.calculate_kappa:
        # Calculate Cohen's κ
        r1_path, r2_path = args.calculate_kappa
        results = pipeline.calculate_cohens_kappa(r1_path, r2_path)
        pipeline.print_kappa_report(results)
        
        # Save results
        output_path = "data/cohens_kappa_results.json"
        with open(output_path, 'w') as f:
            json.dump(results, f, indent=2)
        print(f"\nResults saved to {output_path}")
    
    else:
        print("Please specify an action:")
        print("  --dataset: Create verification form from dataset")
        print("  --create-blank N: Create blank form with N entries")
        print("  --generate-mock form reviewer_id: Generate mock annotations")
        print("  --calculate-kappa r1.json r2.json: Calculate Cohen's κ")
        parser.print_help()


if __name__ == "__main__":
    main()
